In [3]:
import numpy as np     ##(2,1) 2 row  and total element will be 1 in each  [1],[2]
                    ## (2,3)  2 row and total element will be 3 in each row  [[1,2,3],[1,2,3]]

In [4]:
x = np.array([1,2,3,4,5])  #array
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [5]:
y = [1,2,3,4,5]  #list
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


## Difference between Numpy Array and List in Python
- data types storage-
- importing module
- numerical operation
- modification capabilities
- consumes less memory
- fast as compared to the python list
- convenient to use

In [6]:
l= []
for i in range(1,5):
    int_1=int(input('Enter:'))
    l.append(int_1)
print(np.array(l))    

[1 1 2 3]


## Dimensions in array   #ndim function use to check dimension
- 1D array = [1 2 3 4]
- 2D array = [[1 2 3 4]]
- 3D array = [[[1 2 3 4]]]
- Higher Dimensional Array

In [7]:
ar2=np.array([[1,2,3,4],[1,2,3,4]])  #array always looklike list  #2D array
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [8]:
ar3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])  #3D array
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [9]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Special Numpy Array
- array filled with 0's
- array filled with 1's
- create an empty array
- an array with a range of elements
- array diagonal element filled with 1's
- create an array with values that are spaced linearly in a specified interval

## Zeros()

In [10]:
arr_zero = np.zeros(4)
arr_zero1 = np.zeros((3,4))

print(arr_zero)
print()
print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones()

In [11]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))

print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## create an empty array

In [12]:
ar_em = np.empty(4)    #previous data comes in empty array
ar_em1 = np.empty((3,4)) 

print(ar_em)
print()
print(ar_em1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##  arange() - an array with a range of elements

In [13]:
ar_rn = np.arange(4)
print(ar_rn)


[0 1 2 3]


In [14]:
print(np.arange(1,10))
print(np.arange(3.0))
print(np.arange(1,10,2))
print(np.arange(20,dtype=complex))
print(np.arange(1,10,2,dtype=float))    #(start,end,difference)

[1 2 3 4 5 6 7 8 9]
[0. 1. 2.]
[1 3 5 7 9]
[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 17.+0.j
 18.+0.j 19.+0.j]
[1. 3. 5. 7. 9.]


In [15]:
a= np.arange(-10,10,1.25) #last value excluded
print(a)

[-10.    -8.75  -7.5   -6.25  -5.    -3.75  -2.5   -1.25   0.     1.25
   2.5    3.75   5.     6.25   7.5    8.75]


##  eye() - array diagonal element filled with 1's-identity matrix

In [16]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
ar_dia1 = np.eye(3,5)
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## linspace() - create an array with values that are spaced linearly in a specified interval

In [18]:
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [19]:
b= np.linspace(0,1,10) #last value included/divide values equally
print(b)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Create Numpy Array with Random numbers
- rand()- the function is used to generate a random value b/w 0 to 1
- randn()- the function is used to generate a random value clost to zero.This may return positive or negative numbers as well
- ranf()- the function for doing random sampling in numpy.It returns an array of specified shape and fills it with random floats in the half    interval [0.0,1.0)
- randint()- the function is used to generate a random number b/w given range

## rand() - the function is used to generate a random value b/w 0 to 1

In [20]:
var = np.random.rand(4)

print(var)

[0.49541634 0.01946221 0.63228932 0.02037915]


In [21]:
var1 = np.random.rand(2,5)

print(var1)

[[0.27814058 0.4640409  0.15380911 0.6397192  0.13217349]
 [0.24343411 0.786856   0.37676621 0.01273842 0.55007089]]


## randn()- the function is used to generate a random value clost to zero.This may return positive or negative numbers as well

In [22]:
var2 = np.random.randn(5)
print(var2)

[-0.54100013 -0.00488087  0.21809424 -0.78121886 -2.48172376]


In [23]:
var3 = np.random.randn(2,5)
print(var3)

[[ 0.2005457   0.96266846 -0.48811969 -1.2482445  -0.16999572]
 [-0.28988605  1.68545507  0.17785003  0.57448045 -1.09246715]]


## ranf()- the function for doing random sampling in numpy.It returns an array of specified shape and fills it with random floats in the half    interval [0.0,1.0).one is not included

In [24]:
var4 = np.random.ranf(4)
print(var4)

[0.74816268 0.87940778 0.16170078 0.00848955]


## randint()- the function is used to generate a random number b/w given range...min and max value..last value not included

In [25]:
var5 = np.random.randint(5,20,5)    #(min,value,totalvalues)
print(var5)

[16 19 18 18  9]


In [26]:
var6 = np.random.randint(5,20,(3,3))
print(var6)

[[14  9 19]
 [ 8  9 18]
 [ 8 12 14]]


## Data Types

In [27]:
var_1 = np.array([1,2,3,4,5])
print('Data type:',var_1.dtype)

Data type: int32


In [28]:
var_1 = np.array([1.1,2.2,3.3,4.4,5.5])
print('Data type:',var_1.dtype)

Data type: float64


In [29]:
var_1 = np.array(['a','b','c'])   #string datatype
print('Data type:',var_1.dtype)

Data type: <U1


In [30]:
var_1 = np.array(['a','b','c',1,2,3,4])  
print('Data type:',var_1.dtype)

Data type: <U11


#### Datatype conversion

In [31]:
x = np.array([1,2,3,4,5],dtype = np.int8)  #converted int11 to int8

print(x.dtype)

int8


In [32]:
x1 = np.array([1,2,3,4,5],dtype = 'f')  

print(x1.dtype)
print(x1)

float32
[1. 2. 3. 4. 5.]


In [33]:
x2 = np.array([1,2,3,4,5])  
new = np.float32(x2)
new1 = np.int_(new)

print(x2.dtype)
print(new.dtype)
print(new1.dtype)

print(x2)
print(new)
print(new1)

int32
float32
int32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [34]:
x3 = np.array([1,2,3,4,5])  
new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


## Arithmetic operation in numpy array

- a+b  np.add(a,b)
- a-b np.subtract(a,b)
- a*b np.multiply (a,b)
- a/b np.divide(a,b)
- a%b np.mod(a,b)
- a**b np.power(a,b)
- 1/a np.reciprocal(a,b)

## 1D array

In [35]:
vari = np.array([1,2,3,4])
varadd = vari + 3
print(varadd)

[4 5 6 7]


In [36]:
vari = np.array([1,2,3,4])
varadd = np.add(vari,3)
print(varadd)

[4 5 6 7]


In [37]:
vari1 = np.array([1,2,3,4])
vari2 = np.array([1,2,3,4])
varadd1 = vari1 + vari2
print(varadd1)

[2 4 6 8]


In [38]:
vari1 = np.array([1,2,3,4])
vari2 = np.array([1,2,3,4])
varadd1 = np.add(vari1,vari2)
print(varadd1)

[2 4 6 8]


In [39]:
vari = np.array([1,2,3,4])
varadd = vari + 3
print(varadd)

[4 5 6 7]


In [40]:
vari = np.array([1,2,3,4])
varadd = vari * 3
print(varadd)

[ 3  6  9 12]


In [41]:
vari = np.array([1,2,3,4])
varadd = vari / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [42]:
vari = np.array([1,2,3,4])
varadd = vari % 3
print(varadd)

[1 2 0 1]


#### reciprocal

In [43]:
vari = np.array([1,2,3,4])
varadd = np.reciprocal(vari)
print(varadd)

[1 0 0 0]


## 2D array

In [44]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd2= var21 + var22  #use other arithmetic sign
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


## Arithmetic functions
- np.min(x), np.max(x), np.argmin(x), np.sqrt(x), np.sin(x), np.cos(x), np.cumsum(x)

In [45]:
var_2 = np.array([3,2,1,4,5,3,2])
print(np.min(var_2),np.argmin(var_2))   #arg gives the position
print(np.max(var_2),np.argmax(var_2))
print(np.sqrt(var_2))

1 2
5 4
[1.73205081 1.41421356 1.         2.         2.23606798 1.73205081
 1.41421356]


In [46]:
var_3  = np.array([[2,1,3],[9,5,6]])   #axis = 0  col   axis=1 row
var_4 = np.min(var_3,axis=0)
print(var_4)


[2 1 3]


In [47]:
var_3  = np.array([[2,1,3],[9,5,6]])   #axis = 0  col   axis=1 row
var_4 = np.min(var_3,axis=1)
print(var_4)
print(np.argmin(var_4))

[1 5]
0


In [48]:
var_3  = np.array([[2,1,3],[9,5,6]])   #axis = 0  col   axis=1 row
var_4 = np.max(var_3,axis=1)
print(var_4)

[3 9]


In [49]:
var_3  = np.array([[2,1,3],[9,5,6]])   #axis = 0  col   axis=1 row
var_4 = np.max(var_3,axis=0)
print(var_4)


[9 5 6]


In [50]:
var_4 = np.array([1,2,3])

print(np.sin(var_4))
print()
print(np.cos(var_4))
print()
print(np.cumsum(var_4))


[0.84147098 0.90929743 0.14112001]

[ 0.54030231 -0.41614684 -0.9899925 ]

[1 3 6]


## Shaping and Reshaping in numpy array

In [51]:
var_5 = np.array([[1,2,3],[1,2,3]])

print(var_5)
print()
print(var_5.shape)

[[1 2 3]
 [1 2 3]]

(2, 3)


In [52]:
var_6= np.array([1,2,3,4],ndmin=4)

print(var_6)
print(var_6.ndim)
print()
print(var_6.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [53]:
var_7 = np.array([1,2,3,4,5,6])
print(var_7)
print(var_7.ndim)

e= var_7.reshape(3,2)
print(e)
print(e.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


In [54]:
var_8 = np.array([1,2,3,4,5,6,5,6,4,5,8,4])
print(var_8)
print(var_8.ndim)

g= var_8.reshape(2,3,2)  #3D array
print(g)
print(g.ndim)
print()

one= g.reshape(-1)
print(one)
print(one.ndim)

[1 2 3 4 5 6 5 6 4 5 8 4]
1
[[[1 2]
  [3 4]
  [5 6]]

 [[5 6]
  [4 5]
  [8 4]]]
3

[1 2 3 4 5 6 5 6 4 5 8 4]
1


## Broadcasting Array

In [55]:
arr = np.array([1,2,3])                 ##(2,1) 2 row  and total element will be 1 in each
print(arr)                            ## (2,3)  2 row and total element will be 3 in each row
print(arr.shape)
print()

arr1 = np.array([[1],[2],[3]])
print(arr1)
print(arr1.shape)
print()
print(arr+arr1)


[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [56]:
arr2= np.array([[1],[2]])
print(arr2.shape)

arr3= np.array([[1,2,3],[1,2,3]])
print(arr3.shape)
print()
print(arr2+arr3)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


## Indexing and Slicing

## Indexing

In [57]:
va =np.array([9,8,7,6])
print(va[0])
print(va[3])

9
6


In [58]:
va1 =np.array([[9,8,7],[4,5,6]])
print(va1)
print(va1.ndim)
print()
print(va1[0,2])   #(ROW,COL)
print(va1[1,1])

[[9 8 7]
 [4 5 6]]
2

7
5


In [59]:
va2 =np.array([[[1,2],[3,4],]])
print(va2)
print(va2.ndim)
print()
print(va2[0,1,1])


[[[1 2]
  [3 4]]]
3

4


## Slicing

In [60]:
a1=np.array([1,2,3,4,5])   #start:stop+1:step
print(a1[1:4])
print(a1[:])
print(a1[1::2])
print(a1[:3])
print(a1[2:])


[2 3 4]
[1 2 3 4 5]
[2 4]
[1 2 3]
[3 4 5]


In [77]:
a2= np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(a2)
print(a2.ndim)
print()

print(a2[0,:5])
print(a2[1,1:])
print(a2[0:2,1:3])
print(a2[2,:5])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
2

[1 2 3 4 5]
[8 7 6 5]
[[2 3]
 [8 7]]
[11 12 13 14 15]
