In [1]:
import numpy as np     ##(2,1) 2 row  and total element will be 1 in each  [1],[2]
                    ## (2,3)  2 row and total element will be 3 in each row  [[1,2,3],[1,2,3]]

In [2]:
x = np.array([1,2,3,4,5])  #array
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [3]:
y = [1,2,3,4,5]  #list
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


## Difference between Numpy Array and List in Python
- data types storage-
- importing module
- numerical operation
- modification capabilities
- consumes less memory
- fast as compared to the python list
- convenient to use

In [4]:
l= []
for i in range(1,5):
    int_1=int(input('Enter:'))
    l.append(int_1)
print(np.array(l))    

[4 5 6 1]


## Dimensions in array   #ndim function use to check dimension
- 1D array = [1 2 3 4]
- 2D array = [[1 2 3 4]]
- 3D array = [[[1 2 3 4]]]
- Higher Dimensional Array

In [5]:
ar2=np.array([[1,2,3,4],[1,2,3,4]])  #array always looklike list  #2D array
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [6]:
ar3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])  #3D array
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [7]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Special Numpy Array
- array filled with 0's
- array filled with 1's
- create an empty array
- an array with a range of elements
- array diagonal element filled with 1's
- create an array with values that are spaced linearly in a specified interval

## Zeros()

In [8]:
arr_zero = np.zeros(4)
arr_zero1 = np.zeros((3,4))

print(arr_zero)
print()
print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones()

In [9]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))

print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## create an empty array

In [10]:
ar_em = np.empty(4)    #previous data comes in empty array
ar_em1 = np.empty((3,4)) 

print(ar_em)
print()
print(ar_em1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##  arange() - an array with a range of elements

In [11]:
ar_rn = np.arange(4)
print(ar_rn)


[0 1 2 3]


In [12]:
print(np.arange(1,10))
print(np.arange(3.0))
print(np.arange(1,10,2))
print(np.arange(20,dtype=complex))
print(np.arange(1,10,2,dtype=float))    #(start,end,difference)

[1 2 3 4 5 6 7 8 9]
[0. 1. 2.]
[1 3 5 7 9]
[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 17.+0.j
 18.+0.j 19.+0.j]
[1. 3. 5. 7. 9.]


In [13]:
a= np.arange(-10,10,1.25) #last value excluded
print(a)

[-10.    -8.75  -7.5   -6.25  -5.    -3.75  -2.5   -1.25   0.     1.25
   2.5    3.75   5.     6.25   7.5    8.75]


##  eye() - array diagonal element filled with 1's-identity matrix

In [14]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
ar_dia1 = np.eye(3,5)
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## linspace() - create an array with values that are spaced linearly in a specified interval

In [16]:
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [17]:
b= np.linspace(0,1,10) #last value included/divide values equally
print(b)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Create Numpy Array with Random numbers
- rand()- the function is used to generate a random value b/w 0 to 1
- randn()- the function is used to generate a random value clost to zero.This may return positive or negative numbers as well
- ranf()- the function for doing random sampling in numpy.It returns an array of specified shape and fills it with random floats in the half    interval [0.0,1.0)
- randint()- the function is used to generate a random number b/w given range

## rand() - the function is used to generate a random value b/w 0 to 1

In [18]:
var = np.random.rand(4)

print(var)

[0.88753956 0.9996279  0.51029693 0.45014177]


In [19]:
var1 = np.random.rand(2,5)

print(var1)

[[0.74458529 0.27271054 0.29802746 0.67200303 0.15433373]
 [0.92644064 0.89188329 0.64077541 0.94590912 0.67984317]]


## randn()- the function is used to generate a random value clost to zero.This may return positive or negative numbers as well

In [20]:
var2 = np.random.randn(5)
print(var2)

[-0.03765268  0.41954765  0.87818694 -1.37222753  1.17562903]


In [21]:
var3 = np.random.randn(2,5)
print(var3)

[[ 0.21901658  1.18327687 -1.29161045 -1.6812877  -1.25438838]
 [ 0.9550297   1.70539414  0.48953293 -0.77228972 -0.2102638 ]]


## ranf()- the function for doing random sampling in numpy.It returns an array of specified shape and fills it with random floats in the half    interval [0.0,1.0).one is not included

In [22]:
var4 = np.random.ranf(4)
print(var4)

[0.50961229 0.14249304 0.20872073 0.02725519]


## randint()- the function is used to generate a random number b/w given range...min and max value..last value not included

In [23]:
var5 = np.random.randint(5,20,5)    #(min,value,totalvalues)
print(var5)

[ 5  7 13 18  7]


In [24]:
var6 = np.random.randint(5,20,(3,3))
print(var6)

[[10 11 10]
 [ 8 19 16]
 [ 9 12  6]]


## Data Types

In [25]:
var_1 = np.array([1,2,3,4,5])
print('Data type:',var_1.dtype)

Data type: int32


In [26]:
var_1 = np.array([1.1,2.2,3.3,4.4,5.5])
print('Data type:',var_1.dtype)

Data type: float64


In [27]:
var_1 = np.array(['a','b','c'])   #string datatype
print('Data type:',var_1.dtype)

Data type: <U1


In [28]:
var_1 = np.array(['a','b','c',1,2,3,4])  
print('Data type:',var_1.dtype)

Data type: <U11


#### Datatype conversion

In [29]:
x = np.array([1,2,3,4,5],dtype = np.int8)  #converted int11 to int8

print(x.dtype)

int8


In [30]:
x1 = np.array([1,2,3,4,5],dtype = 'f')  

print(x1.dtype)
print(x1)

float32
[1. 2. 3. 4. 5.]


In [31]:
x2 = np.array([1,2,3,4,5])  
new = np.float32(x2)
new1 = np.int_(new)

print(x2.dtype)
print(new.dtype)
print(new1.dtype)

print(x2)
print(new)
print(new1)

int32
float32
int32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [32]:
x3 = np.array([1,2,3,4,5])  
new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


## Arithmetic operation in numpy array

- a+b  np.add(a,b)
- a-b np.subtract(a,b)
- a*b np.multiply (a,b)
- a/b np.divide(a,b)
- a%b np.mod(a,b)
- a**b np.power(a,b)
- 1/a np.reciprocal(a,b)

## 1D array

In [33]:
vari = np.array([1,2,3,4])
varadd = vari + 3
print(varadd)

[4 5 6 7]


In [34]:
vari = np.array([1,2,3,4])
varadd = np.add(vari,3)
print(varadd)

[4 5 6 7]


In [35]:
vari1 = np.array([1,2,3,4])
vari2 = np.array([1,2,3,4])
varadd1 = vari1 + vari2
print(varadd1)

[2 4 6 8]


In [36]:
vari1 = np.array([1,2,3,4])
vari2 = np.array([1,2,3,4])
varadd1 = np.add(vari1,vari2)
print(varadd1)

[2 4 6 8]


In [37]:
vari = np.array([1,2,3,4])
varadd = vari + 3
print(varadd)

[4 5 6 7]


In [38]:
vari = np.array([1,2,3,4])
varadd = vari * 3
print(varadd)

[ 3  6  9 12]


In [39]:
vari = np.array([1,2,3,4])
varadd = vari / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [40]:
vari = np.array([1,2,3,4])
varadd = vari % 3
print(varadd)

[1 2 0 1]


#### reciprocal

In [41]:
vari = np.array([1,2,3,4])
varadd = np.reciprocal(vari)
print(varadd)

[1 0 0 0]


## 2D array

In [42]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd2= var21 + var22  #use other arithmetic sign
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


## Arithmetic functions
- np.min(x), np.max(x), np.argmin(x), np.sqrt(x), np.sin(x), np.cos(x), np.cumsum(x)

In [43]:
var_2 = np.array([3,2,1,4,5,3,2])
print(np.min(var_2),np.argmin(var_2))   #arg gives the position
print(np.max(var_2),np.argmax(var_2))
print(np.sqrt(var_2))

1 2
5 4
[1.73205081 1.41421356 1.         2.         2.23606798 1.73205081
 1.41421356]


In [44]:
var_3  = np.array([[2,1,3],[9,5,6]])   #axis = 0  col   axis=1 row
var_4 = np.min(var_3,axis=0)
print(var_4)


[2 1 3]


In [45]:
var_3  = np.array([[2,1,3],[9,5,6]])   #axis = 0  col   axis=1 row
var_4 = np.min(var_3,axis=1)
print(var_4)
print(np.argmin(var_4))

[1 5]
0


In [46]:
var_3  = np.array([[2,1,3],[9,5,6]])   #axis = 0  col   axis=1 row
var_4 = np.max(var_3,axis=1)
print(var_4)

[3 9]


In [47]:
var_3  = np.array([[2,1,3],[9,5,6]])   #axis = 0  col   axis=1 row
var_4 = np.max(var_3,axis=0)
print(var_4)


[9 5 6]


In [48]:
var_4 = np.array([1,2,3])

print(np.sin(var_4))
print()
print(np.cos(var_4))
print()
print(np.cumsum(var_4))


[0.84147098 0.90929743 0.14112001]

[ 0.54030231 -0.41614684 -0.9899925 ]

[1 3 6]


## Shaping and Reshaping in numpy array

In [49]:
var_5 = np.array([[1,2,3],[1,2,3]])

print(var_5)
print()
print(var_5.shape)

[[1 2 3]
 [1 2 3]]

(2, 3)


In [50]:
var_6= np.array([1,2,3,4],ndmin=4)

print(var_6)
print(var_6.ndim)
print()
print(var_6.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [51]:
var_7 = np.array([1,2,3,4,5,6])
print(var_7)
print(var_7.ndim)

e= var_7.reshape(3,2)
print(e)
print(e.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


In [52]:
var_8 = np.array([1,2,3,4,5,6,5,6,4,5,8,4])
print(var_8)
print(var_8.ndim)

g= var_8.reshape(2,3,2)  #3D array
print(g)
print(g.ndim)
print()

one= g.reshape(-1)
print(one)
print(one.ndim)

[1 2 3 4 5 6 5 6 4 5 8 4]
1
[[[1 2]
  [3 4]
  [5 6]]

 [[5 6]
  [4 5]
  [8 4]]]
3

[1 2 3 4 5 6 5 6 4 5 8 4]
1


## Broadcasting Array

In [53]:
arr = np.array([1,2,3])                 ##(2,1) 2 row  and total element will be 1 in each
print(arr)                            ## (2,3)  2 row and total element will be 3 in each row
print(arr.shape)
print()

arr1 = np.array([[1],[2],[3]])
print(arr1)
print(arr1.shape)
print()
print(arr+arr1)


[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [54]:
arr2= np.array([[1],[2]])
print(arr2.shape)

arr3= np.array([[1,2,3],[1,2,3]])
print(arr3.shape)
print()
print(arr2+arr3)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


## Indexing and Slicing

## Indexing

In [55]:
va =np.array([9,8,7,6])
print(va[0])
print(va[3])

9
6


In [56]:
va1 =np.array([[9,8,7],[4,5,6]])
print(va1)
print(va1.ndim)
print()
print(va1[0,2])   #(ROW,COL)
print(va1[1,1])

[[9 8 7]
 [4 5 6]]
2

7
5


In [57]:
va2 =np.array([[[1,2],[3,4],]])
print(va2)
print(va2.ndim)
print()
print(va2[0,1,1])


[[[1 2]
  [3 4]]]
3

4


## Slicing

In [58]:
a1=np.array([1,2,3,4,5])   #start:stop+1:step
print(a1[1:4])
print(a1[:])
print(a1[1::2])
print(a1[:3])
print(a1[2:])


[2 3 4]
[1 2 3 4 5]
[2 4]
[1 2 3]
[3 4 5]


In [59]:
a2= np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(a2)
print(a2.ndim)
print()

print(a2[0,:5])
print(a2[1,1:])
print(a2[0:2,1:3])
print(a2[2,:5])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
2

[1 2 3 4 5]
[8 7 6 5]
[[2 3]
 [8 7]]
[11 12 13 14 15]


In [60]:
var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


## Iterating Numpy Arrays -nditer()

In [61]:
var_2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var_2)
print()

for j in var_2:
    print(j)

print()

for k in var_2:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [63]:
var_3 = np.array([[[1,2,3],[1,2,3]]])
print(var_3)

print(var_3.ndim)
print()
for i in var_3:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [1 2 3]]]
3

1
2
3
1
2
3


In [64]:
var_4 = np.array([[[1,2,3],[1,2,3]]])
print(var_4)

print(var_4.ndim)
print()

for i in np.nditer(var_4):
    print(i)

[[[1 2 3]
  [1 2 3]]]
3

1
2
3
1
2
3


In [ ]:
var_5 = np.array([[[1,2,3],[1,2,3]]])
print(var_5)

print(var_5.ndim)
print()

for i in np.nditer(var_5):
    print(i)

In [65]:
var_5 = np.array([[[1,2,3],[1,2,3]]])
print(var_5)

print(var_5.ndim)
print()

for i in np.nditer(var_5,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[1 2 3]
  [1 2 3]]]
3

b'1'
b'2'
b'3'
b'1'
b'2'
b'3'


## ndenumerate-gives index value

In [66]:
var_6 = np.array([[1,2,3],[1,2,3]])
print(var_6)

print(var_6.ndim)
print()

for i,d in np.ndenumerate(var_6):
    print(i,d)

[[1 2 3]
 [1 2 3]]
2

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 1
(1, 1) 2
(1, 2) 3


## Copy Vs View in Numpy Arrays
- copy owns the data while view does not own the date
- changes made in the coy data does not reflect in the original array.
- any changes made to the wiew will affectthe original array,and any changes made to the original array will affect the view

In [67]:
num1=np.array([1,2,3,4])
co = num1.copy()

print("var:",num1)
print("copy:",co)

var: [1 2 3 4]
copy: [1 2 3 4]


In [68]:
x = np.array([9,8,7,6,5])
vi = x.view()
print('x:',x)
print('view:',vi)

x: [9 8 7 6 5]
view: [9 8 7 6 5]


In [70]:
num2=np.array([1,2,3,4])
co1 = num2.copy()
num2[1]=40

print("var:",num2)
print("copy:",co1)

var: [ 1 40  3  4]
copy: [1 2 3 4]


In [73]:
x1 = np.array([9,8,7,6,5])
vi1 = x1.view()
x1[1]=40
print('x:',x1)
print('view:',vi1)

x: [ 9 40  7  6  5]
view: [ 9 40  7  6  5]


## Join and Split Array

In [74]:
y1= np.array([1,2,3,4])  #1D array
y2= np.array([9,8,7,5])
ar= np.concatenate((y1,y2))
print(ar)

[1 2 3 4 9 8 7 5]


In [77]:
y3= np.array([[1,2],[3,4]])  #2D array
y4= np.array([[9,8],[7,5]])
ar1= np.concatenate((y3,y4),axis=1)
print(y3)
print()
print(y4)
print()
print(ar1)

[[1 2]
 [3 4]]

[[9 8]
 [7 5]]

[[1 2 9 8]
 [3 4 7 5]]


In [78]:
ar1= np.concatenate((y3,y4),axis=0)  
print(ar1)

[[1 2]
 [3 4]
 [9 8]
 [7 5]]


In [79]:
y_1= np.array([1,2,3,4])  #1D array
y_2= np.array([9,8,7,5])

a_new =np.stack((y_1,y_2),axis = 1)
print(a_new)

[[1 9]
 [2 8]
 [3 7]
 [4 5]]


In [82]:
a_new =np.hstack((y_1,y_2))
print(a_new)

[1 2 3 4 9 8 7 5]


In [83]:
a_new =np.vstack((y_1,y_2))
print(a_new)

[[1 2 3 4]
 [9 8 7 5]]


In [84]:
a_new =np.dstack((y_1,y_2))
print(a_new)

[[[1 9]
  [2 8]
  [3 7]
  [4 5]]]


In [87]:
y_1= np.array([1,2,3,4]) 
y_2= np.array([9,8,7,5])

a_n = np.stack((y_1,y_2),axis=1) #row
a_n4 = np.stack((y_1,y_2),axis=0) #col
a_n1 = np.hstack((y_1,y_2)) #row
a_n2 = np.vstack((y_1,y_2)) #col
a_n3 = np.dstack((y_1,y_2)) #height

print(a_n)
print()
print(a_n4)
print()
print(a_n1)
print()
print(a_n2)
print()
print(a_n3)


[[1 9]
 [2 8]
 [3 7]
 [4 5]]

[[1 2 3 4]
 [9 8 7 5]]

[1 2 3 4 9 8 7 5]

[[1 2 3 4]
 [9 8 7 5]]

[[[1 9]
  [2 8]
  [3 7]
  [4 5]]]


## Split()

In [93]:
vr = np.array([1,2,3,4,5,6])
print(vr)
ar_1 =np.array_split(vr,3)
print(ar_1)
print(type(ar_1))
print(ar_1[0])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


In [96]:
vr1 = np.array([[1,2],[3,4],[5,6]])
print(vr1)
ar_2 =np.array_split(vr1,3)
print(ar_2)
print()


[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]



In [95]:
vr1 = np.array([[1,2],[3,4],[5,6]])
print(vr1)
ar_2 =np.array_split(vr1,3)
ar_3 =np.array_split(vr1,3,axis=1)
print(ar_2)
print()
print(ar_3)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
